# Generated by Django 2.2.4 on 2019-09-01 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('genre', models.IntegerField(choices=[(-1, 'not defined'), (0, 'rock'), (1, 'metal'), (2, 'pop'), (3, 'hip-hop'), (4, 'electronic'), (5, 'reggae'), (6, 'other')], default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ConcertCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('artistic_name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealConcert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('place', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('facebook_page', models.URLField(blank=True, max_length=128, null=True)),
                ('bands', models.ManyToManyField(related_name='real_concerts', to='concerts.Band')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_concerts', to='concerts.ConcertCity')),
                ('likes', models.ManyToManyField(related_name='real_concerts_likes', to=settings.AUTH_USER_MODEL)),
                ('persons', models.ManyToManyField(related_name='real_concerts', to='concerts.Person')),
            ],
        ),
        migrations.CreateModel(
            name='DreamConcert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bands', models.ManyToManyField(related_name='dream_concerts', to='concerts.Band')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='concerts.ConcertCity')),
                ('likes', models.ManyToManyField(related_name='dream_concerts_likes', to=settings.AUTH_USER_MODEL)),
                ('persons', models.ManyToManyField(related_name='dream_concerts', to='concerts.Person')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='persons',
            field=models.ManyToManyField(to='concerts.Person'),
        ),
    ]
