# Generated by Django 2.2.4 on 2019-09-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='persons',
            field=models.ManyToManyField(related_name='bands', to='concerts.Person'),
        ),
    ]
