# Generated by Django 2.2.4 on 2019-09-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_auto_20190901_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='artistic_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
