# Generated by Django 2.2.4 on 2019-09-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_auto_20190904_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realconcert',
            name='facebook_page',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
