# Generated by Django 2.2.4 on 2019-09-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_auto_20190904_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertcity',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
