# Generated by Django 2.2.4 on 2019-12-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_auto_20190906_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realconcert',
            name='bands',
            field=models.ManyToManyField(blank=True, null=True, related_name='real_concerts', to='concerts.Band'),
        ),
    ]
